import discord

aqua = discord.Color(int("00e0e0", 16))
class Color_list:
    list = discord.Embed(title = "Color", type = "rich", color = aqua, description = "")
    list.add_field(name = "名稱", value = "\
                    red\n\
                    dark_red\n\
                    pink\n\
                    orange\n\
                    gold\n\
                    dark_gold\n\
                    light_green\n\
                    green\n\
                    teal\n\
                    dark_teal\n\
                    cyan\n\
                    aqua\n\
                    blue\n\
                    lavender\n\
                    light_purple\n\
                    purple\n\
                    magenta\n\
                    dark_magenta\n\
                    brown\n\
                    blurple\n\
                    greyple\n\
                    white\n\
                    lighter_gray\n\
                    light_gray\n\
                    dark_gray\n\
                    darker_gray\n\
                    black\n\
                    dark_theme")
    list.add_field(name = "顏色", value = "\
                    紅色\n\
                    深紅色\n\
                    粉紅色\n\
                    橘色\n\
                    金色\n\
                    深金色\n\
                    淺綠色\n\
                    綠色\n\
                    藍綠色\n\
                    深藍綠色\n\
                    青色\n\
                    水藍色\n\
                    藍色\n\
                    薰衣草紫\n\
                    淺紫色\n\
                    紫色\n\
                    洋紅色\n\
                    深洋紅色\n\
                    棕色\n\
                    藍紫色\n\
                    灰紫色\n\
                    白色\n\
                    亮灰色\n\
                    淺灰色\n\
                    深灰色\n\
                    暗灰色\n\
                    黑色\n\
                    深色背景")
    list.add_field(name = "色碼", value = "\
                    #E74C3C\n\
                    #992D22\n\
                    #FFC0CB\n\
                    #E67E22\n\
                    #F1C40F\n\
                    #C27C0E\n\
                    #2ECC71\n\
                    #1F8B4C\n\
                    #1ABC9C\n\
                    #11806A\n\
                    #206694\n\
                    #00E0E0\n\
                    #3498DB\n\
                    #B57EDC\n\
                    #9B56B6\n\
                    #71368A\n\
                    #E91E63\n\
                    #AD1457\n\
                    #A84300\n\
                    #7289DA\n\
                    #99AAB5\n\
                    #FFFFFF\n\
                    #95A5A6\n\
                    #979C9F\n\
                    #607D8B\n\
                    #546E7A\n\
                    #010101\n\
                    #36393F")